# Generated by Django 4.0.6 on 2022-07-21 15:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_friend_request_from_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2022, 7, 21, 15, 10, 1, 315570, tzinfo=utc))),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='account.profile')),
            ],
        ),
    ]
